live_url: https://trackparliamentaryquestions.service.gov.uk
mail_from: Al Equipo <ingenierofelipeurrego@gmail.com>
mail_reply_to: ingenierofelipeurrego@gmail.com
mail_tech_support: pqsupport@digital.justice.gov.uk
http_client_timeout: 20
commission_mail_from: Al Equipo <ingenierofelipeurrego@gmail.com
healthcheck_pqa_api_interval: 15               # minimum interval between pqa API healthchecks in minutes
key_metric_threshold: 0.5

excepted_from_ssl:
  - ping.json

mail_worker:
  pid_filepath: '/tmp/mail_worker.pid'
  max_fail_count: 15
  timeout: 300

gecko_warning_levels:
  num_emails_waiting: 15
  num_emails_abandoned: 1
  pctg_answered_tokens: 50

smoke_test_runner:
  out_file: '/tmp/smoke_test_run'

